AWSTemplateFormatVersion: "2010-09-09"

Description: >-
  Instance NAT
Parameters:

  NetworkStackName:
    Description: >-
      Nom de la stack reseau
    Type: String
    MinLength: 1
    MaxLength: 255
    AllowedPattern: '^[a-zA-Z][-a-zA-Z0-9]*$'
    Default: network

  SGStackName:
    Description: >-
      Nom de la stack des groupes de securite
    Type: String
    MinLength: 1
    MaxLength: 255
    AllowedPattern: '^[a-zA-Z][-a-zA-Z0-9]*$'
    Default: SG

  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instances
    Type: 'AWS::EC2::KeyPair::KeyName'
    ConstraintDescription: must be the name of an existing EC2 KeyPair.

Resources:

# --------- PROFIL IAM -------- #
  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles: [ FullAccessS3 ]

# -------- INSTANCE ROUTEUR NAT -------- #
  NATInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-00798d7180f25aac2
      InstanceType: t2.micro
      KeyName: !Ref KeyName
      IamInstanceProfile: !Ref InstanceProfile
      NetworkInterfaces:
        - DeviceIndex: '0'
          SubnetId: !ImportValue
            'Fn::Sub': '${NetworkStackName}-PublicSubnetC'
          AssociatePublicIpAddress: true                # Association d'une adresse publique
          GroupSet:
            - !ImportValue
              'Fn::Sub': '${SGStackName}-NATSG'

      SourceDestCheck: false  # Permet d'utiliser la fonction NAT dans une instance
      Tags:
        - Key: Name
          Value: !Sub NAT-${AWS::StackName}
#      UserData: #  Installation de la fonction routeur dans l'instance Linux
#        Fn::Base64: !Sub |
#          #!/bin/bash
#          yum -y update
#          yum install -y aws-cfn-bootstrap
#          echo 1 > /proc/sys/net/ipv4/ip_forward
#          echo 0 > /proc/sys/net/ipv4/conf/eth0/send_redirects
#          /sbin/iptables -t nat -A POSTROUTING -o eth0 -s 0.0.0.0/0 -j MASQUERADE
#          /sbin/iptables-save > /etc/sysconfig/iptables
#          mkdir -p /etc/sysctl.d/
#          cat << NatConfFileMarker > /etc/sysctl.d/nat.conf
#          net.ipv4.ip_forward = 1
#          net.ipv4.conf.eth0.send_redirects = 0
#          NatConfFileMarker
#          /opt/aws/bin/cfn-signal -e 0 --resource NATInstance --stack ${AWS::StackName} --region ${AWS::Region}
#    # L'installation est complete après la réception d'un signal dans un délai de 5 minutes, la ligne ci-dessus retourne le signal souhaité
#    CreationPolicy:
#      ResourceSignal:
#        Count: 1
#        Timeout: PT5M

# -------- ROUTES VERS NAT POUR LES RESEAUX PRIVES -------- #
  PrivateRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !ImportValue
        'Fn::Sub': '${NetworkStackName}-VPC'

  RouteToNat:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PrivateRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      InstanceId: !Ref NATInstance

  PrivateSubnetRouteTableAssociation1:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !ImportValue
        'Fn::Sub': '${NetworkStackName}-PrivateSubnetA'
      RouteTableId: !Ref PrivateRouteTable

  PrivateSubnetRouteTableAssociation2:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !ImportValue
        'Fn::Sub': '${NetworkStackName}-PrivateSubnetB'
      RouteTableId: !Ref PrivateRouteTable

  PrivateSubnetRouteTableAssociation3:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !ImportValue
        'Fn::Sub': '${NetworkStackName}-PrivateSubnetC'
      RouteTableId: !Ref PrivateRouteTable

# -------- EXPORTS -------- #
Outputs:

  InstanceProfile:
    Description: Profile d'instance
    Value: !Ref InstanceProfile
    Export:
      Name: !Sub ${AWS::StackName}-IntProfil

  NatInstance:
    Description: Instance ID
    Value: !Ref NATInstance
    Export:
      Name: !Sub ${AWS::StackName}-NATInstance


  PublicIp:
    Value:
      Fn::GetAtt:
        - NATInstance
        - PublicIp
    Description: IP Public NAT





# aws cloudformation deploy --template-file 3_VPN_instance.yaml --stack-name NAT --capabilities CAPABILITY_NAMED_IAM --parameter-overrides KeyName=tp-terraform
