#!/bin/bash
sudo amazon-linux-extras install epel
sudo amazon-linux-extras install docker
sudo service docker start
sudo systemctl enable docker
sudo usermod -a -G docker ec2-user
sudo yum -y install fuse fuse-libs
sudo yum -y install python-pip
pip install yas3fs
sudo sed -i'' 's/^# *user_allow_other/user_allow_other/' /etc/fuse.conf
mkdir /home/ec2-user/local-mnt
sudo yum groupinstall -y "Development Tools"
pip install docker-compose
yas3fs s3://projet10 /home/ec2-user/local-mnt
systemctl stop httpd
cd /home/ec2-user/
echo $(pwd) >> /home/ec2-user/install
docker-compose up -d
echo "Fin PostInstall" >> /home/ec2-user/install