version: '3.3'

services:

   wordpress:
     image: wordpress:latest
     ports:
       - "80:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: ${DB_HOST}
       WORDPRESS_DB_USER: ${DB_USER}
       WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
       WORDPRESS_DB_NAME: ${DB_NAME}
     volumes:
      - uploads:/var/www/html/wp-content/:nocopy


volumes:
  uploads:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/ec2-user/local-mnt/'

